DATA:
  BATCH_SIZE: 1024
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  USE_RMSNORM: True
  USE_GROUPNORM: True
  USE_SWIGLU: True
  USE_DIFFATTN: True
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  WEIGHT_DECAY: 0.05
  BASE_LR: 1e-3
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
  CLIP_GRAD: 1.0